title: <p align="center"> Darshan BV </p>
logo: /assets/img/Darshan_Photo.jpeg

description:
  <p align="center">
  <a href="/docs/Resume-Darshan_BV.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/darshan-bv-830714a7/">LinkedIn</a> |
  <a href="https://github.com/Darshan-BV">GitHub</a>
  
  <br>
  I am Working as Senior Software Engineer at Cisco Systems.I have hands on in all the stages of software development cycle.
  My tasks involve analysing software code, altering software code, fixing bugs & Customer debug sessions.
  I have currently 10 years of experience, with a focus on Software Design and Development, with involvement in features like 
  Hardware Offload for Cisco Firepower Threat Defence Platform Software Development for Cisco Firepower platforms.
  Also I am Certified ScrumMaster from Scrum Alliance 
  <br>
  </p>



theme: jekyll-theme-minimal
